services:
  database:
    image: 'postgres:16.10-alpine3.22'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
